ALGORITMO "Tipos de Dados"
VAR 
numero_casa: inteiro
saldo_bancario, valor_saque: real
fila_clientes: vetor [1..10] de real
coordenadas_x_y: vetor [0..4, 8..10] de inteiro
nome_aluno: caractere
estado_lampada: logico

INICIO
numero_casa <- 28
saldo_bancario <- 58.7
valor_saque <- (saldo_bancario - 23)
fila_clientes[1] <- 23
coordenadas_x_y[3,9] <- 12
nome_aluno <- "Sunna"
estado_lampada <- FALSO

FIMALGORITMO
