ALGORITMO "Tamanho de Dados Enviados Para o Dispositivo de Saida"
VAR 
ninfa: caractere
poema: caractere

INICIO
ninfa <- "Sunna" + ": "
Escreva(ninfa)
Escreval("Ola, Mundo Cruel!": 10) // envio de 10 caracteres

Escreva(ninfa)
Escreval("Ola, Mundo Cruel!")


poema <- "A mente e um fogo a ser aceso, nao um vaso a preencher."
Escreva(ninfa)
Escreval(poema:29)

Escreva(ninfa)
Escreval(poema)

FIMALGORITMO
