Algoritmo "Operador Divisao"
//github.com/juniobash

    Var
        primeiroNumero : inteiro
        segundoNumero : inteiro
        divisao: real

    Inicio
        Escreval("Divisao de dois Numero")

        Escreva("Digite um numero Inteiro: ")
        Leia(primeiroNumero)
          
        Escreva("Digite outro numero Inteiro: ")
        Leia(segundoNumero)

        divisao := (primeiroNumero / segundoNumero)
        Escreval("Resultado:", divisao)

FimAlgoritmo