Algoritmo "Operador Soma"
//github.com/juniobash

    Var
        primeiroNumero : inteiro
        segundoNumero : inteiro
        soma: inteiro

    Inicio
        Escreval("Soma de dois Numero")

        Escreva("Digite um numero Inteiro: ")
        Leia(primeiroNumero)
          
        Escreva("Digite outro numero Inteiro: ")
        Leia(segundoNumero)

        soma := (primeiroNumero + segundoNumero)
        Escreval("Resultado:", soma)

FimAlgoritmo