Algoritmo "Operador subtracao"
//github.com/juniobash

    Var
        primeiroNumero : inteiro
        segundoNumero : inteiro
        subtracao: inteiro

    Inicio
        Escreval("Subtracao de dois Numero")

        Escreva("Digite um numero Inteiro: ")
        Leia(primeiroNumero)
          
        Escreva("Digite outro numero Inteiro: ")
        Leia(segundoNumero)

        subtracao := (primeiroNumero - segundoNumero)
        Escreval("Resultado:", subtracao)

FimAlgoritmo